"""
This module creates cool human-readable names based on a given numeric id.
"""


def get_name(id, words=4):
    words_lists = []
    result = []

    if words <= 2:
        words_lists = [ADJECTIVES, NOUNS][:words]
    else:
        words_lists = [ADJECTIVES] * (words - 1) + [NOUNS]

    for words in words_lists:
        result.append(words[id % len(words)])
        id = int(id / len(words))

    return "".join(result)


NOUNS = [
    "Moose",
    "Unicorn",
    "Pony",
    "Crucible",
    "Marker",
    "Commitment",
    "Carbon",
    "Rhino",
    "Cream",
    "Herring",
    "Chicken",
    "Raptor",
    "Rock",
    "Elephant",
    "Milk",
    "Donkey",
    "Burger",
    "Faggot",
    "Pizza",
    "Stoning",
    "Snake",
    "Lizard",
    "Ship",
    "Wizard",
    "Cow",
    "Beef",
    "Cheese",
    "Garden",
    "Shed",
    "Delusion",
    "Theft",
    "Car",
    "Robbery",
    "Battery",
    "Assault",
    "Bat",
    "Bukkake",
    "Racket",
    "Ball",
    "Neighborhood",
    "Beak",
    "Goatfucker",
    "Clustertruck",
    "Boat",
    "Ship",
    "Shipment",
    "Salami",
    "Cheese",
    "Pan",
    "Noodle",
    "Hottie",
    "Edgelord",
    "Fedora",
    "Feces",
    "Facehugger",
    "Troll",
    "Meme",
    "Casserole",
    "Lasagna",
    "Stew",
    "Banana",
    "Pineapple",
    "Shroom",
    "Bark",
    "Boomerang",
    "Gangbang",
    "Crew",
    "Statue",
    "Memorial",
    "Park",
    "Graffiti",
    "Shitstorm",
    "Pepe",
    "Hooker",
    "Phallus",
    "Erection",
    "Poop",
    "Shit",
    "Fuck",
    "Motherfuck",
    "Ripperoni",
    "Bride",
    "Gringo",
    "Content",
    "Hipster",
    "Balls",
    "Hitler",
    "Sex",
    "Psychorapist",
    "Racist",
    "Trump",
    "Politician"
]

ADJECTIVES = [
    "Brazen",
    "Bitchy",
    "Sweaty",
    "Racist",
    "Halal",
    "Kinky",
    "Steamy",
    "Dead",
    "Mecha",
    "Shaved",
    "Conditioned",
    "Reconditioned",
    "Mesmerizing",
    "Creamy",
    "Rekt",
    "Crispy",
    "Cheerful",
    "Greasy",
    "Jurassic",
    "Disgusting",
    "Slimy",
    "Shipped",
    "Frozen",
    "DeepFried",
    "Liquid",
    "Dried",
    "Dry",
    "Deep",
    "Deeper",
    "Deepest",
    "Dank",
    "Indecent",
    "HumanReadable",
    "Hard",
    "Red",
    "Rotten",
    "Forgiving",
    "Angry",
    "Deceased",
    "Infuriated",
    "Welcoming",
    "Silly",
    "Witless",
    "Estranged",
    "Inviting",
    "Grand",
    "Massive",
    "Tiny",
    "Genuine",
    "Grateful",
    "Unforgiving"
    "Late",
    "Enraged",
    "Timely",
    "Gracious",
    "Grumpy",
    "Old",
    "Young",
    "Yellow",
    "Green",
    "Blue",
    "Creaky",
    "Cranky",
    "Dim",
    "Bright",
    "Sharp",
    "Dull",
    "Exciting",
    "Boring",
    "Enticing",
    "Little",
    "Renowned",
    "Known",
    "Famous",
    "Diabolical",
    "Heavenly",
    "Satisfying",
    "Grateful",
    "Committed",
    "Playful",
    "Greedy",
    "Needy",
    "Hateful",
    "Dental",
    "Mental",
    "Devious",
    "Clandestine",
    "Sneaky",
    "Quiet",
    "Silent",
    "Loud",
    "Loudest",
    "Louder",
    "Squeaky",
    "Hanged",
    "Hooked",
    "Cooked",
    "Baked",
    "Indispensable",
    "Incontinent",
    "Indirect",
    "Insightful",
    "Smart",
    "Reliable",
    "Gentrified",
    "Retarded",
    "Penetrated",
    "Interchangeable",
    "Destructible",
    "Dismissive",
    "Permissive",
    "Polite",
    "Offensive",
    "Possessive",
    "Aging",
    "Stoned",
    "Vegetarian",
    "Nigerian",
    "High",
    "Erect"
]

NOUNS = sorted(set(NOUNS))
ADJECTIVES = sorted(set(ADJECTIVES))
