"""
This module creates cool human-readable names based on a given numeric id.
"""


def get_name(id, words=4):
    words_lists = []
    res = []
    if words <= 2:
        words_lists = [ADJECTIVES, NOUNS][:words]
    else:
        words_lists = [ADJECTIVES] * (words - 1) + [NOUNS]
    for words in words_lists:
        res.append(words[id % len(words)])
        id = int(id / len(words))
    return "".join(res)


NOUNS = [
    "Moose",
    "Unicorn",
    "Pony",
    "Crucible",
    "Marker",
    "Commitment",
    "Carbon",
    "Rhino",
    "Cream",
    "Herring",
    "Chicken",
    "Dinosaur",
    "Rock",
    "Elephant",
    "Milk",
    "Donkey",
    "Burger",
    "Pizza",
    "Stoning",
    "Snake",
    "Lizard",
    "Ship",
    "Wizard",
    "Cow",
    "Beef",
    "Cheese",
    "Garden",
    "Shed",
    "Delusion",
    "Theft",
    "Car",
    "Robbery",
    "Battery",
    "Assault",
    "Bat",
    "Racket",
    "Ball",
    "Neighborhood",
    "Beak",
    "Goat",
    "Truck",
    "Boat",
    "Ship",
    "Shipment",
    "Salami",
    "Cheese",
    "Pan",
    "Noodle",
    "Casserole",
    "Lasagna",
    "Stew",
    "Banana",
    "Pineapple",
    "Mushroom",
    "Bark",
    "Boomerang",
    "Gang",
    "Crew",
    "Statue",
    "Memorial",
    "Park",
    "Graffiti"
]

ADJECTIVES = [
    "Brazen",
    "Conditioned",
    "Reconditioned",
    "Mesmerizing",
    "Creamy",
    "Crispy",
    "Cheerful",
    "Greasy",
    "Disgusting",
    "Slimy",
    "Shipped",
    "Frozen",
    "Fried",
    "Liquid",
    "Dried",
    "Dry",
    "Deep",
    "Hard",
    "Red",
    "Rotten",
    "Forgiving",
    "Angry",
    "Deceased",
    "Infuriated",
    "Welcoming",
    "Silly",
    "Witless",
    "Estranged",
    "Inviting",
    "Grand",
    "Massive",
    "Tiny",
    "Genuine",
    "Grateful",
    "Unforgiving"
    "Late",
    "Enraged",
    "Timely",
    "Gracious",
    "Grumpy",
    "Old",
    "Young",
    "Yellow",
    "Green",
    "Blue",
    "Creaky",
    "Cranky",
    "Dim",
    "Bright",
    "Sharp",
    "Dull",
    "Exciting",
    "Boring",
    "Enticing",
    "Little",
    "Renowned",
    "Known",
    "Famous",
    "Diabolical",
    "Heavenly",
    "Satisfying",
    "Grateful",
    "Committed",
    "Playful",
    "Greedy",
    "Needy",
    "Hateful",
    "Dental",
    "Mental",
    "Devious",
    "Clandestine",
    "Sneaky",
    "Quiet",
    "Silent",
    "Loud",
    "Loudest",
    "Louder",
    "Squeaky",
    "Hanged",
    "Hooked",
    "Cooked",
    "Baked",
    "Indispensable",
    "Incontinent",
    "Indirect",
    "Insightful",
    "Smart",
    "Reliable",
    "Gentrified",
    "Retarded",
    "Penetrated",
    "Interchangeable",
    "Destructible",
    "Dismissive",
    "Permissive",
    "Polite",
    "Offensive",
    "Possessive",
    "Aging"
]

NOUNS = sorted(set(NOUNS))
ADJECTIVES = sorted(set(ADJECTIVES))
